### ISSUE TITLE
Getting error opening admin page

### ISSUE THREAD

**Issue by chillpilllike** [medusajs/b2b-starter-medusa#114]
- Creating server
✔ Server is ready on http://localhost:9000 – 18ms
info:    Admin URL → http://localhost:9000/app
Does the file exist?
Does the file exist?
Does the file exist?
virtual:medusa/forms:1:41
virtual:medusa/forms:1:41
Does the file exist?
Does the file exist?
Does the file exist?
virtual:medusa/menu-items:1:41
virtual:medusa/menu-items:1:41
Does the file exist?
Does the file exist?
Does the file exist?
Does the file exist?
virtual:medusa/routes:1:30
virtual:medusa/routes:1:30
http:    GET / ← https://g5edov.easypanel.host/ (404) - 35.239 ms
http:    GET /app ← - (304) - 38.025 ms
http:    GET /app/entry.tsx ← https://medusa-b2b-b2b-backend.g5edov.easypanel.host/app (200) - 0.810 ms
http:    GET /app/index.css ← https://medusa-b2b-b2b-backend.g5edov.easypanel.host/app (304) - 2171.906 ms
7:34:27 AM [vite] Internal server error: Failed to resolve import "/backend/src/admin/routes/companies/page.tsx" from "virtual:medusa/forms". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:medusa/forms:1:41
  1  |  import { config as RouteConfig0 } from "/app/backend/src/admin/routes/companies/page.tsx"
     |                                          ^
  2  |  import { config as RouteConfig1 } from "/app/backend/src/admin/routes/quotes/page.tsx"
  3  |  
      at TransformPluginContext._formatError (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49255:41)
      at TransformPluginContext.error (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49250:16)
      at normalizeUrl (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64041:23)
      at async file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
      at async Promise.all (index 0)
      at async TransformPluginContext.transform (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64100:7)
      at async PluginContainer.transform (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49096:18)
      at async loadAndTransform (file:///app/backend/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51929:27)

**Comment by brooktewabe** [comment]
Same issue here works fine locally but when I dockerize it I keep seeing this errors on docker desktop

**Comment by brooktewabe** [comment]
Niceee 
Now the app runs fine but keep getting MedusaError: column p3.product_id does not exist when I try to see products list

**Comment by kasperkristensen** [comment]
> Niceee @kasperkristensen Now the app runs fine but keep getting MedusaError: column p3.product_id does not exist when I try to see products list

Remember to run migrations `npx medusa db:migrate`
