### ISSUE TITLE
DELETE Address not working

### ISSUE THREAD

**Issue by fxmb** [medusajs/b2b-starter-medusa#125]
There seems to be an issue with the "DELETE customer address" from the profile section. I noticed this in the B2B starter. When using the SDK the route returns this:

```
error:   Requested fields [id, company, customer_id, first_name, last_name, address_1, address_2, city, province, postal_code, country_code, phone, metadata, created_at, updated_at] are not valid
MedusaError: Requested fields [id, company, customer_id, first_name, last_name, address_1, address_2, city, province, postal_code, country_code, phone, metadata, created_at, updated_at] are not valid
    at prepareListQuery (/path/to/node_modules/@medusajs/framework/src/http/utils/get-query-config.ts:179:11)
    at prepareRetrieveQuery (/path/to/node_modules/@medusajs/framework/src/http/utils/get-query-config.ts:245:45)
    at validateQuery (/path/to/node_modules/@medusajs/framework/src/http/utils/validate-query.ts:85:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  __isMedusaError: true,
  type: 'invalid_data',
  code: undefined,
  date: 2024-12-10T08:49:14.067Z
}
```

This is the request from the storefront:

```
export const deleteCustomerAddress = async (
  addressId: string
): Promise<void> => {
  await sdk.store.customer
    .deleteAddress(addressId)
    .then(() => {
      revalidateTag("customer")
      return { success: true, error: null }
    })
    .catch((err) => {
      return { success: false, error: err.toString() }
    })
}
```

So some of the validator is probably not correct. Could it be that some of the customer_address fields are not part of or wrongly part of the default selects?

**Comment by VariableVic** [comment]
Thanks for the report! I've created an internal ticket as this seems to be an issue with the customer address API, not this Starter. I'll keep you posted.

**Comment by fxmb** [comment]
Why was this marked as closed? Its still not working (at least on our end)?
