### ISSUE TITLE
Error restarting the server after updating any backend file

### ISSUE THREAD

**Issue by rida-re** [medusajs/b2b-starter-medusa#38]
Hello,
my server gets an error kill EPERM when I make a modification to any backend file, here is my error:  

`medusa-starter-default:dev: info:    src\api\store\wishlists\route.ts modified: Restarting dev server
medusa-starter-default:dev: Error: kill EPERM
medusa-starter-default:dev:     at ChildProcess.kill (node:internal/child_process:511:26)
medusa-starter-default:dev:     at Object.restart (C:\Users\Rida\worksapace\medusa\b2b-starter-medusa\node_modules\@medusajs\medusa\src\commands\develop.ts:79:27)
medusa-starter-default:dev:     at FSWatcher.<anonymous> (C:\Users\Rida\worksapace\medusa\b2b-starter-medusa\node_modules\@medusajs\medusa\src\commands\develop.ts:117:14)
medusa-starter-default:dev:     at FSWatcher.emit (node:events:519:28)
medusa-starter-default:dev:     at FSWatcher.emit (node:domain:488:12)
medusa-starter-default:dev:     at FSWatcher.emitWithAll (C:\Users\Rida\worksapace\medusa\b2b-starter-medusa\node_modules\chokidar\index.js:540:8)
medusa-starter-default:dev:     at FSWatcher._emit (C:\Users\Rida\worksapace\medusa\b2b-starter-medusa\node_modules\chokidar\index.js:632:8)
medusa-starter-default:dev:     at listener (C:\Users\Rida\worksapace\medusa\b2b-starter-medusa\node_modules\chokidar\lib\nodefs-handler.js:370:20) {
medusa-starter-default:dev:   errno: -4048,
medusa-starter-default:dev:   code: 'EPERM',
medusa-starter-default:dev:   syscall: 'kill'
medusa-starter-default:dev: }`

Windows : 64
even if with cmd in administrator mode 
![image](https://github.com/user-attachments/assets/f9f262d4-4456-4ae0-aa43-b4dc5c8d19b9)

**Comment by rida-rechrache** [comment]
hello @VariableVic 

Thanks for getting back to me! It seems to be Medusa-specific as I haven't encountered similar issues with other Node projects. 
I'm currently running Node version 
![image](https://github.com/user-attachments/assets/1e45c3a7-08cf-4252-866d-338f64f21d6c)

, which should be compatible with Medusa.

I do have full write-access, so I might give WSL a shot as you suggested. I'll keep you updated if I run into any other problems or find a solution. If don't know other users face the same issue, I'll definitely let you know!

Thanks again for the help.

**Comment by riqwan** [comment]
Hey @rida-rechrache is this still an issue?

**Comment by rida-rechrache** [comment]
Hi @riqwan 
Yes, I always have this issue on my Windows,
I tried to install WSL on my Windows, but I don't have enough space for that.

**Comment by riqwan** [comment]
Let me push the latest release version, maybe its already been fixed.

**Comment by riqwan** [comment]
@rida-rechrache can you try a fresh install and see if its still showing up?

**Comment by rida-rechrache** [comment]
Hi @riqwan
Even with the migration of Medusa, I always have this issue on my Windows.

**Comment by riqwan** [comment]
@rida-rechrache I'm back on Monday, will help debug this once I'm back. Let me know if you've progressed in the meantime.

**Comment by rida-rechrache** [comment]
Hi @riqwan 
Even with the migration of Medusa & next 15, I always have this issue on my Windows.

![image](https://github.com/user-attachments/assets/b7bc9caa-e1ab-4916-ba9f-ca50f1ef8867)

**Comment by riqwan** [comment]
We've removed the monorepo, can you try with the new version of the repo on develop? If the issue still persists, then this issue should be lodged here - https://github.com/medusajs/medusa/issues

**Comment by VariableVic** [comment]
Closing due to inactivity.
