### ISSUE TITLE
Error when run 'yarn dev'

### ISSUE THREAD

**Issue by BenYegq** [medusajs/b2b-starter-medusa#48]
Hi there, 
I already finished all the previously steps and got error message after hitting "yarn dev":

a@a-dev-server:/opt/b2b-starter-medusa$ yarn dev
turbo 2.1.3

 WARNING  stale pid file at "/tmp/turbod/39e04d7838c96450/turbod.pid"
  × Could not find "@starter/types#build-packages" in root turbo.json or "build-packages" in package
    ╭─[turbo.json:8:1]
  8 │     "dev": {
  9 │       "dependsOn": ["^build-packages"],
    ·                     ─────────────────
 10 │       "persistent": true,
    ╰────

**Comment by rida-rechrache** [comment]
hele @BenYegq ,
I encountered the same error and fixed it by modifying the turbo.json file with the following code : 

`{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": [".next/**", "!.next/cache/**"]
    },
    "dev": {
      "persistent": true,
      "cache": false
    }
  }
}
`

**Comment by chrislicodes** [comment]
After making the adjustment by @rida-rechrache I ran into this issue again:

```
❯ yarn dev
turbo 2.1.3

• Packages in scope: @starter/types, medusa-next, medusa-starter-default
• Running dev in 3 packages
• Remote caching disabled
medusa-starter-default:dev: cache bypass, force executing 5caf4ca6c61f88f7
medusa-next:dev: cache bypass, force executing cd32cef9188fbbb3
medusa-next:dev:   ▲ Next.js 14.2.15
medusa-next:dev:   - Local:        http://localhost:8000
medusa-next:dev:   - Environments: .env
medusa-next:dev:
medusa-next:dev:  ✓ Starting...
medusa-starter-default:dev: info:    Watching filesystem to reload dev server on file change
medusa-starter-default:dev: redisUrl not found. A fake redis instance will be used.
medusa-starter-default:dev: warn:    Local Event Bus installed. This is not recommended for production.
medusa-starter-default:dev: warn:    Failed to load countries, skipping loader. Original error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
medusa-starter-default:dev: warn:    Failed to load currencies, skipping loader. Original error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
medusa-starter-default:dev: error:   Could not resolve module: Payment. Error: Loaders for module Payment failed: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
medusa-starter-default:dev:
medusa-starter-default:dev: error:   Error starting server
medusa-starter-default:dev: Error: Loaders for module Payment failed: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
medusa-starter-default:dev:     at runLoaders (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:413:14)
medusa-starter-default:dev:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
medusa-starter-default:dev:     at async loadInternalModule (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/loaders/utils/load-internal.ts:181:17)
medusa-starter-default:dev:     at async loadModule (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:85:10)
medusa-starter-default:dev:     at async moduleLoader (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/loaders/module-loader.ts:21:32)
medusa-starter-default:dev:     at async Function.bootstrap_ (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:484:9)
medusa-starter-default:dev:     at async Function.bootstrapAll (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/medusa-module.ts:302:12)
medusa-starter-default:dev:     at async loadModules (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:152:19)
medusa-starter-default:dev:     at async MedusaApp_ (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:384:22)
medusa-starter-default:dev:     at async MedusaApp (/Users/chris/Projects/examples/b2b-starter-medusa/node_modules/@medusajs/modules-sdk/src/medusa-app.ts:587:10)
```

**Comment by rida-rechrache** [comment]
Hello @chrislicodes,

I think you have a connection problem with the database. Could you run this command to check?

Navigate to this folder: cd \b2b-starter-medusa\apps\backend
Then run: yarn seed

**Comment by BenYegq** [comment]
> hele @BenYegq , I encountered the same error and fixed it by modifying the turbo.json file with the following code :
> 
> `{ "$schema": "https://turbo.build/schema.json", "tasks": { "build": { "dependsOn": ["^build"], "outputs": [".next/**", "!.next/cache/**"] }, "dev": { "persistent": true, "cache": false } } } `

Thank you @rida-rechrache , it works!

**Comment by chrislicodes** [comment]
I figured it out, thanks for the responses @rida-rechrache!

**Comment by BenYegq** [comment]
issue fixed.

**Comment by rida-rechrache** [comment]
@BenYegq close your ticket

**Comment by riqwan** [comment]
Apologies for seeing this late! 🫶 Great to hear that it was resolved!
