### ISSUE TITLE
Error: yarn install && yarn setup failed

### ISSUE THREAD

**Issue by souvrard** [medusajs/b2b-starter-medusa#79]
Hello,

Is this starter ready ? 

I have dependencies errors with yarn install and yarn setup exit with npm error :/

Debian 12
Node v20.18.0
Npm 10.8.2
Yarn 4.5.1

output of "yarn install":
```
➤ YN0000: · Yarn 4.5.1
➤ YN0000: ┌ Project validation
➤ YN0057: │ medusa-next: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + typescript@patch:typescript@npm%3A5.6.3#optional!builtin<compat/typescript>::version=5.6.3&hash=8c6c40, fsevents@patch:fsevents@npm%3A2.3.3#optional!builtin<compat/fsevents>::version=2.3.3&hash=df0bf1, and 2 more.
➤ YN0085: │ - fsevents@patch:fsevents@npm%3A2.3.3#~builtin<compat/fsevents>::version=2.3.3&hash=18f3a7, resolve@patch:resolve@npm%3A1.22.8#~builtin<compat/resolve>::version=1.22.8&hash=07638b, and 2 more.
➤ YN0000: └ Completed in 21s 830ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ @starter/types@workspace:packages/types doesn't provide awilix (pa53cf), requested by @medusajs/types.
➤ YN0002: │ medusa-next@workspace:apps/storefront doesn't provide awilix (p06206), requested by @medusajs/types.
➤ YN0002: │ medusa-starter-default@workspace:apps/backend doesn't provide tailwindcss (pfc110), requested by @medusajs/ui-preset.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1689 packages were added to the project (+ 123.41 MiB).
➤ YN0000: └ Completed in 19s 718ms
➤ YN0000: ┌ Link step
➤ YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ @medusajs/telemetry@npm:2.0.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0007: │ msgpackr-extract@npm:3.0.3 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.5.7 [4b8dd] must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.5.7 [72229] must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 3s 571ms
➤ YN0000: · Done with warnings in 45s 592ms
```
output of "yarn setup":
```
turbo 2.2.3

• Packages in scope: @starter/types
• Running build in 1 packages
• Remote caching disabled
@starter/types:build: cache hit (outputs already on disk), replaying logs 32ee8588d3b567fd
@starter/types:build: 

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    89ms >>> FULL TURBO

npm warn config ignoring workspace config at /home/stxxxxx/medusajs/b2b-starter-medusa/apps/backend/.npmrc
npm error could not determine executable to run
npm error A complete log of this run can be found in: /home/stxxxxx/.npm/_logs/2024-11-05T14_45_20_313Z-debug-0.log
```
and the log file:
```
0 verbose cli /home/stxxxxx/.nvm/versions/node/v20.18.0/bin/node /home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.8.2
2 info using node@v20.18.0
3 silly config load:file:/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/npmrc
4 warn config ignoring workspace config at /home/stxxxxx/medusajs/b2b-starter-medusa/apps/backend/.npmrc
5 info config found workspace root at /home/stxxxxx/medusajs/b2b-starter-medusa
6 silly config load:file:/home/stxxxxx/medusajs/b2b-starter-medusa/.npmrc
7 silly config load:file:/home/stxxxxx/.npmrc
8 silly config load:file:/home/stxxxxx/.nvm/versions/node/v20.18.0/etc/npmrc
9 verbose title npm exec medusa db:create
10 verbose argv "exec" "--" "medusa" "db:create"
11 verbose logfile logs-max:10 dir:/home/stxxxxx/.npm/_logs/2024-11-05T14_45_20_313Z-
12 verbose logfile /home/stxxxxx/.npm/_logs/2024-11-05T14_45_20_313Z-debug-0.log
13 silly logfile start cleaning logs, removing 1 files
14 silly logfile done cleaning log files
15 silly packumentCache heap:2197815296 maxSize:549453824 maxEntrySize:274726912
16 http fetch GET 200 https://registry.npmjs.org/medusa 1841ms (cache revalidated)
17 verbose stack Error: could not determine executable to run
17 verbose stack     at getBinFromManifest (/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
17 verbose stack     at exec (/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:202:15)
17 verbose stack     at async Exec.execWorkspaces (/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/commands/exec.js:37:7)
17 verbose stack     at async Npm.exec (/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/npm.js:207:9)
17 verbose stack     at async module.exports (/home/stxxxxx/.nvm/versions/node/v20.18.0/lib/node_modules/npm/lib/cli/entry.js:74:5)
18 verbose pkgid medusa@0.0.3
19 error could not determine executable to run
20 verbose cwd /home/stxxxxx/medusajs/b2b-starter-medusa/apps/backend
21 verbose os Linux 6.1.0-26-amd64
22 verbose node v20.18.0
23 verbose npm  v10.8.2
24 verbose exit 1
25 verbose code 1
26 error A complete log of this run can be found in: /home/stxxxxx/.npm/_logs/2024-11-05T14_45_20_313Z-debug-0.log
```

Stephane

**Comment by andresdvelez** [comment]
Hello, I'm getting the same error when trying to install deps 🌵

**Comment by Satwikloka** [comment]
![Screenshot 2024-11-11 161814](https://github.com/user-attachments/assets/319573e5-c06c-49c2-b8d4-38e831e0a689)
Hey there! I am facing this error which is similar to this issue

kindly help us with this issue.

**Comment by VariableVic** [comment]
Hey all,

Looks like the local types package is causing some trouble. However, I'm unable to reproduce these issues locally. Did you follow these steps?

```
# Clone the repository
git clone https://github.com/medusajs/b2b-starter-medusa.git

# Go to the folder
cd ./b2b-starter-medusa

# Install dependencies & setup medusa storefront & backend
yarn install && yarn setup

# Start Servers - storefront & backend
yarn dev
```

Also, make sure you're on the `develop` branch.

My local versions:
- Yarn 4.5.1
- Node v22.9.0
- NPM 10.8.3

Maybe @riqwan can chime in here as he did the setup on the shared types package.

**Comment by riqwan** [comment]
Hey guys, apologies for the delay as I was on vacation. 

@souvrard @andresdvelez @Satwikloka have you been able to figure this out yet? If not, can you run the steps within `yarn setup` individually and scope out the error? 

Additionally, would be helpful to see which OS, yarn versions you're using.

**Comment by JohnGemstone** [comment]
Make sure the repo package `@starter/types` is built before you go to build next or the medusa app. This can be done by running `yarn build-packages` from the root.

**Comment by souvrard** [comment]
Hi,
@riqwan yes, Yes I finally managed to install and test the application, but I can't explain how I did it :/
I have deleted all files and reinstalled...
I have build the project, run setup, re-build.... downgraded yarn from 4.5.1 to 4.5.0 and finally, all is working now !!

I will try to reproduce theses error...

**Comment by riqwan** [comment]
Thanks, yes the yarn setup is only tested on a local version. glad it works now!
